#!/usr/bin/env bash
#  script that configures a server

# sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
# service nginx restart

# Stop Nginx service
sudo service nginx stop

# Check if any process is already listening on port 80
if sudo lsof -Pi :80 -sTCP:LISTEN -t >/dev/null; then
    # If a process is found, stop it
    sudo kill -9 $(sudo lsof -t -i:80)
fi

# Modify Nginx configuration file to listen on port 80
sudo sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default

# Start Nginx service
sudo service nginx start

# Check Nginx error logs for any issues
sudo tail -n 50 /var/log/nginx/error.log
