#!/usr/bin/env bash
# nginx running as user nginx on 8080
# Ensure Nginx is installed
if ! dpkg -l | grep -q nginx; then
    apt-get update
    apt-get install -y nginx
fi

# Modify Nginx config to listen on port 8080
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/nginx.conf

# Change Nginx user to nginx
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
# sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start



# # Change Nginx user in the configuration
# # sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
# # Modify the default site configuration to listen on port 8080
# sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default

# # Remove the default Nginx site configuration
# rm /etc/nginx/sites-enabled/default

# # Restart Nginx
# service nginx restart
